const books = [
  {
    _id: '1',
    name: 'Python for Programmers',
    image: '/images/Python for Programmers.jpg',
    description:
      'Written for programmers with a background in another high-level language, Python for Programmers uses hands-on instruction to teach today’s most compelling, leading-edge computing technologies and programming in Python—one of the world’s most popular and fastest-growing languages.',
    authors: 'Paul J. Deitel, Harvey Deitel',
    publishers: 'Addison-Wesley Professional',
    isbn: 9780135231364,
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Grokking Algorithms',
    image: '/images/Grokking Algorithms.jpg',
    description:
      'Grokking Algorithms is a friendly take on this core computer science topic. In it, you will learn how to apply common algorithms to the practical programming problems you face every day.',
    authors: 'Aditya Bhargava, Jed Limke',
    publishers: 'Manning Publications',
    isbn: 9781617292231,
    price: 99.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Introducing Go',
    image: '/images/Introducing Go.jpg',
    description:
      'Perfect for beginners familiar with programming basics, this hands-on guide provides an easy introduction to Go, the general-purpose programming language from Google.',
    authors: 'Caleb Doxsey',
    publishers: "O'Reilly Media",
    isbn: 9781491941959,
    price: 49.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Software Engineering at Google',
    image: '/images/Software Engineering at Google.jpg',
    description:
      'Today, software engineers need to know not only how to program effectively but also how to develop proper engineering practices to make their codebase sustainable and healthy. This book emphasizes this difference between programming and software engineering.',
    authors: 'Titus Winters, Tom Manshreck, Hyrum Wright',
    publishers: "O'Reilly Media",
    isbn: 9781492082798,
    price: 79.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Analytical Skills for AI and Data Science',
    image: '/images/Analytical Skills for AI and Data Science.jpg',
    description:
      'While several market-leading companies have successfully transformed their business models by following data- and AI-driven paths, the vast majority have yet to reap the benefits.',
    authors: 'Daniel Vaughan',
    publishers: "O'Reilly Media",
    isbn: 9781492060949,
    price: 59.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'JavaScript: The Definitive Guide',
    image: '/images/JavaScript: The Definitive Guide.jpg',
    description:
      'JavaScript is the programming language of the web and is used by more software developers today than any other programming language.',
    authors: 'David Flanagan',
    publishers: "O'Reilly Media",
    isbn: 9781491952023,
    price: 39.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
];

export default books;
